import { Article, Category, User, Blog } from '@/app/types';

// Mock data for articles
export const articles: Article[] = [
  // Featured articles (first 3)
  {
    id: '1',
    title: 'Minimalism Never Goes Out of Style',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'design',
    author: 'Naruto Uzumaki',
    authorAvatar: '/images/avatars/user-01.jpg',
    publishDate: 'September 06, 2016',
    featuredImage: '/images/thumbs/featured/featured-1.jpg',
    tags: ['design', 'minimalism'],
    postFormat: 'standard',
  },
  {
    id: '2',
    title: 'Enhancing Your Designs with Negative Space',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'design',
    author: 'Sasuke Uchiha',
    authorAvatar: '/images/avatars/user-02.jpg',
    publishDate: 'August 29, 2016',
    featuredImage: '/images/thumbs/featured/featured-2.jpg',
    tags: ['design', 'space'],
    postFormat: 'standard',
  },
  {
    id: '3',
    title: 'Music Album Cover Designs for Inspiration',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'design',
    author: 'Naruto Uzumaki',
    authorAvatar: '/images/avatars/user-01.jpg',
    publishDate: 'August 27, 2016',
    featuredImage: '/images/thumbs/featured/featured-3.jpg',
    tags: ['design', 'music'],
    postFormat: 'standard',
  },
  // Regular articles
  {
    id: '4',
    title: 'Just a Standard Format Post.',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'design',
    author: 'Jonathan Doe',
    authorAvatar: '/images/avatars/user-01.jpg',
    publishDate: '2024-03-15',
    featuredImage: '/images/thumbs/diagonal-building.jpg',
    tags: ['design', 'photography'],
    postFormat: 'standard',
  },
  {
    id: '5',
    title: 'This Is Another Standard Format Post.',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'design',
    author: 'Jane Smith',
    authorAvatar: '/images/avatars/user-02.jpg',
    publishDate: '2024-03-14',
    featuredImage: '/images/thumbs/ferris-wheel.jpg',
    tags: ['design', 'ui'],
    postFormat: 'standard',
  },
  {
    id: '6',
    title: 'This Is a Audio Format Post.',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'design',
    author: 'Mike Johnson',
    authorAvatar: '/images/avatars/user-03.jpg',
    publishDate: '2024-03-13',
    featuredImage: '/images/thumbs/concert.jpg',
    tags: ['design', 'music'],
    postFormat: 'audio',
    audioUrl: '/media/AirReview-Landmarks-02-ChasingCorporate.mp3',
  },
  {
    id: '7',
    title: 'Design Quote',
    excerpt: '',
    content: '<p>Full article content goes here...</p>',
    category: 'design',
    author: 'Dieter Rams',
    authorAvatar: '/images/avatars/user-01.jpg',
    publishDate: '2024-03-12',
    featuredImage: '',
    tags: ['design', 'inspiration'],
    postFormat: 'quote',
    quote: 'Good design is making something intelligible and memorable. Great design is making something memorable and meaningful.',
    quoteAuthor: 'Dieter Rams',
  },
  {
    id: '8',
    title: 'Photography Skills Can Improve Your Graphic Design.',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'photography',
    author: 'Sarah Williams',
    authorAvatar: '/images/avatars/user-04.jpg',
    publishDate: '2024-03-11',
    featuredImage: '/images/thumbs/shutterbug.jpg',
    tags: ['photography', 'html'],
    postFormat: 'standard',
  },
  {
    id: '9',
    title: 'The 10 Golden Rules of Clean Simple Design.',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'branding',
    author: 'David Brown',
    authorAvatar: '/images/avatars/user-05.jpg',
    publishDate: '2024-03-10',
    featuredImage: '/images/thumbs/usaf-rocket.jpg',
    tags: ['branding', 'mockup'],
    postFormat: 'standard',
  },
  {
    id: '10',
    title: 'Workspace Design Trends and Ideas.',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'branding',
    author: 'Jonathan Doe',
    authorAvatar: '/images/avatars/user-01.jpg',
    publishDate: '2024-03-09',
    featuredImage: '/images/thumbs/gallery/work1.jpg',
    tags: ['branding', 'wordpress'],
    postFormat: 'gallery',
    galleryImages: [
      '/images/thumbs/gallery/work1.jpg',
      '/images/thumbs/gallery/work2.jpg',
      '/images/thumbs/gallery/work3.jpg',
    ],
  },
  {
    id: '11',
    title: 'Affordable Web Hosting',
    excerpt: '',
    content: '<p>Full article content goes here...</p>',
    category: 'technology',
    author: 'Jonathan Doe',
    authorAvatar: '/images/avatars/user-01.jpg',
    publishDate: '2024-03-08',
    featuredImage: '',
    tags: ['hosting', 'web'],
    postFormat: 'link',
    linkUrl: 'http://www.dreamhost.com/r.cgi?287326',
    linkDescription: 'Looking for affordable & reliable web hosting? We recommend Dreamhost.',
  },
  {
    id: '12',
    title: 'You Can See Patterns Everywhere.',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'design',
    author: 'Jane Smith',
    authorAvatar: '/images/avatars/user-02.jpg',
    publishDate: '2024-03-07',
    featuredImage: '/images/thumbs/diagonal-pattern.jpg',
    tags: ['design', 'ui'],
    postFormat: 'standard',
  },
  {
    id: '13',
    title: 'This Is a Video Post Format.',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'design',
    author: 'Mike Johnson',
    authorAvatar: '/images/avatars/user-03.jpg',
    publishDate: '2024-03-06',
    featuredImage: '/images/thumbs/ottawa-bokeh.jpg',
    tags: ['design', 'branding'],
    postFormat: 'video',
    videoUrl: 'http://player.vimeo.com/video/14592941?title=0&byline=0&portrait=0&color=F64B39',
  },
  {
    id: '14',
    title: 'Breathtaking Photos of Lighthouses.',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'photography',
    author: 'Sarah Williams',
    authorAvatar: '/images/avatars/user-04.jpg',
    publishDate: '2024-03-05',
    featuredImage: '/images/thumbs/lighthouse.jpg',
    tags: ['photography', 'design'],
    postFormat: 'standard',
  },
  {
    id: '15',
    title: 'Designing With Black and White.',
    excerpt: 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim.',
    content: '<p>Full article content goes here...</p>',
    category: 'branding',
    author: 'David Brown',
    authorAvatar: '/images/avatars/user-05.jpg',
    publishDate: '2024-03-04',
    featuredImage: '/images/thumbs/liberty.jpg',
    tags: ['branding', 'html'],
    postFormat: 'standard',
  },
];

// Mock data for categories
export const categories: Category[] = [
  { id: '1', name: 'Design', slug: 'design', description: 'Design trends and tips', count: 8 },
  { id: '2', name: 'Photography', slug: 'photography', description: 'Photography tutorials', count: 2 },
  { id: '3', name: 'Branding', slug: 'branding', description: 'Branding articles', count: 3 },
  { id: '4', name: 'Music', slug: 'music', description: 'Music and audio content', count: 1 },
  { id: '5', name: 'Technology', slug: 'technology', description: 'Tech news and reviews', count: 1 },
  { id: '6', name: 'Wordpress', slug: 'wordpress', description: 'Wordpress tips', count: 0 },
  { id: '7', name: 'HTML', slug: 'html', description: 'HTML tutorials', count: 0 },
  { id: '8', name: 'UI', slug: 'ui', description: 'UI design', count: 0 },
  { id: '9', name: 'Mockups', slug: 'mockups', description: 'Mockups and resources', count: 0 },
];

// Mock user for authentication
export const users: User[] = [
  {
    id: '1',
    email: 'admin@example.com',
    name: 'Admin User',
    role: 'admin',
  },
  {
    id: '2',
    email: 'editor@example.com',
    name: 'Editor User',
    role: 'editor',
  },
];

// Mock data for blogs
export const blogs: Blog[] = [
  {
    id: '1',
    title: 'Getting Started with React 19',
    slug: 'getting-started-react-19',
    excerpt: 'Learn about the new features and improvements in React 19, including better server components and enhanced performance.',
    content: '<p>React 19 brings exciting new features...</p>',
    author: 'Admin User',
    authorAvatar: '/images/avatars/user-01.jpg',
    publishDate: '2025-12-20',
    featuredImage: '/images/thumbs/featured/featured-1.jpg',
    tags: ['react', 'javascript', 'web-development'],
    status: 'published',
    views: 245,
  },
  {
    id: '2',
    title: 'Building Scalable APIs with Next.js',
    slug: 'building-scalable-apis-nextjs',
    excerpt: 'A comprehensive guide to creating robust and scalable API routes in Next.js applications.',
    content: '<p>Next.js API routes provide a powerful way...</p>',
    author: 'Admin User',
    authorAvatar: '/images/avatars/user-01.jpg',
    publishDate: '2025-12-18',
    featuredImage: '/images/thumbs/featured/featured-2.jpg',
    tags: ['nextjs', 'api', 'backend'],
    status: 'published',
    views: 189,
  },
  {
    id: '3',
    title: 'TypeScript Best Practices 2025',
    slug: 'typescript-best-practices-2025',
    excerpt: 'Discover the latest TypeScript best practices and patterns for writing maintainable code.',
    content: '<p>TypeScript has evolved significantly...</p>',
    author: 'Editor User',
    authorAvatar: '/images/avatars/user-02.jpg',
    publishDate: '2025-12-15',
    featuredImage: '/images/thumbs/featured/featured-3.jpg',
    tags: ['typescript', 'programming', 'best-practices'],
    status: 'published',
    views: 312,
  },
  {
    id: '4',
    title: 'Draft: Advanced Tailwind CSS Techniques',
    slug: 'advanced-tailwind-css-techniques',
    excerpt: 'This is a draft post about advanced Tailwind CSS techniques and customization strategies.',
    content: '<p>Coming soon...</p>',
    author: 'Admin User',
    authorAvatar: '/images/avatars/user-01.jpg',
    publishDate: '2025-12-27',
    featuredImage: '/images/thumbs/diagonal-building.jpg',
    tags: ['css', 'tailwind', 'design'],
    status: 'draft',
    views: 0,
  },
];

// Password: admin123 (hashed)
export const userPasswords: Record<string, string> = {
  'admin@example.com': '$2a$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Will be properly hashed
  'editor@example.com': '$2a$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Will be properly hashed
};
